---

- hosts: localhost
  connection: local
  sudo: yes

  vars:
  - wp_cli_phar: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - wp_cli_bin_path: /usr/local/bin/wp
  - wp_cli_filename: wp-cli.phar
  - root_directory: /home
  - apache_root: /var/www/html
  - mysql_root_password: password
  - wp_directory_name: wordpress
  - wp_mysql_dbname: wordpress
  - wp_mysql_user: wordpress
  - wp_mysql_password: password
  - wp_mysql_prefix: wp_
  - wp_home_url: http://127.0.0.1/{{ wp_directory_name }}
  - wp_site_title: Opsta
  - wp_admin_user: admin
  - wp_admin_password: password
  - wp_admin_email: admin@weerapat.com

  roles:
  - update
  - php
  - apache
  - mysql
  - wp-cli
  - wordpress
