---

- name: Create MySQL Database
  mysql_db:
    name="{{ wp_mysql_dbname }}"
    login_password="{{ mysql_root_password }}"

- name: Create MySQL user
  mysql_user:
    login_password="{{ mysql_root_password }}"
    name="{{ wp_mysql_user }}"
    password="{{ wp_mysql_password }}"
    priv=*.*:ALL
